# prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules/alert.rules.yml"

scrape_configs:
  - job_name: 'url-shortener'
    static_configs:
      - targets: ['url-shortener:5000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
