# prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules/alert.rules.yml"

scrape_configs:
  - job_name: 'ecommerce-app'
    static_configs:
      - targets: ['url-shortener:5000']  # اسم الـ container نفسه بس الاسم القديم
        labels:
          service: 'techstore'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']